version: "3.8"
services:
  database:
    container_name: boardgame-manager-database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=boardgameManagerDB
      - POSTGRES_USER=zenika
      - POSTGRES_PASSWORD=secret